### ISSUE TITLE
Elemental kiss_fft missing

### ISSUE THREAD

**Issue by jeffhammond** [devinamatthews/aquarius#6]
For some reason, I do not get libkiss_fft with Elemental (git master as of two hours ago) on NERSC Edison.  Because of this, AQUARIUS configure fails.  Since AQUARIUS does not need this library, perhaps there is a way to not look for it.

**Comment by devinamatthews** [comment]
You can set --with-elemental-libs when configuring as needed.

Devin

**Comment by jeffhammond** [comment]
But it's more fun if configure "just works" :-)
