### ISSUE TITLE
CCSD guess for CCSDT

### ISSUE THREAD

**Issue by jturney** [devinamatthews/aquarius#7]
I'm having trouble converging a CCSDT wave function with the standard guess. Is it possible use converged CCSD amplitudes as the starting point for CCSDT?

**Comment by devinamatthews** [comment]
Commit 2da702e65b0339f6bd39973daf9c3d7308a7ba85 adds an option to use a CCSD guess for CCSDT and a CCSD or CCSDT guess for CCSDTQ. To use just add "guess ccsd" to the ccsdt input section and add a ccsd task.

**Comment by jturney** [comment]
Excellent, thanks! I'll give it a try later today.
